In [2]:
from pathlib import Path
import pandas as pd

ruta = Path.home() / "proyecto_danper/datasets/produccion"

archivos = sorted(ruta.glob("*.xlsx"))

print("Total de archivos:", len(archivos))

for archivo in archivos:
    print("\nArchivo:", archivo.name)
    excel = pd.ExcelFile(archivo)
    print("Hojas disponibles:", excel.sheet_names)

Total de archivos: 6

Archivo: PROVINCIA ASCOPE_2024-2025.xlsx
Hojas disponibles: ['Ascope', 'Casa Grande', 'Chicama', 'Chocope', 'Magdalena de Cao', 'Paijan', 'Razuri', 'Santiago de Cao', 'Provincia Ascope']

Archivo: PROVINCIA CHEPEN_2024-2025.xlsx
Hojas disponibles: ['Chepen', 'Pacanga', 'Pueblo Nuevo', 'Provincia Chepen']

Archivo: PROVINCIA GRAN_CHIMU_2024-2025.xlsx
Hojas disponibles: ['Cascas', 'Lucma', 'Marmot', 'Sayapullo', 'Provincia Gran Chimu']

Archivo: PROVINCIA PACASMAYO_2024-2025.xlsx
Hojas disponibles: ['San Pedro de Lloc', 'Guadalupe', 'Jequetepeque', 'Pacasmayo', 'San Jose', 'Provincia Pacasmayo']

Archivo: PROVINCIA TRUJILLO_2024-2025.xlsx
Hojas disponibles: ['Trujillo', 'El Porvenir', 'Huanchaco', 'Laredo', 'Moche', 'Poroto', 'Salaverry', 'Simbal', 'Victor Larco', 'Provincia Trujillo']

Archivo: PROVINCIA VIRU_2024-2025.xlsx
Hojas disponibles: ['Viru', 'Chao', 'Guadalupito', 'Provincia Viru']

In [3]:
# Inspeccionar las primeras filas de una hoja real

archivo = ruta / "PROVINCIA VIRU_2024-2025.xlsx"

df_muestra = pd.read_excel(
    archivo,
    sheet_name="Viru",
    header=None
)

print("Dimensiones:", df_muestra.shape)

display(df_muestra.head(20))

Dimensiones: (304, 21)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,FECHA :,2026-01-27 17:22:43.450000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DEPARTAMENTO,PROVINCIA,DISTRITO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LA LIBERTAD,VIRU,VIRU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,EJECUCION Y PERSPECTIVAS DE LA INFORMACION AGR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CAMPAÑA AGRICOLA:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COSECHAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,SIEMBRAS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,COD.CULTIVO,CULTIVO,VARIABLES,TOTAL EJEC.,AGO,SET,OCT,NOV,DIC,ENE,...,MAR,ABR,MAY,JUN,JUL,AGO,SET,OCT,NOV,DIC
11,14030020101,AJI AMARILLO,Sup.Verde (ha.),NaN,16,14,13,12,10,10,...,10,19,16,16,11,34,38,41,50,57
12,NaN,NaN,Siembras (ha.),35,7,2,NaN,1,NaN,5,...,5,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,Sup Perdida (ha.),4,NaN,NaN,NaN,NaN,NaN,NaN,...,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,Cosechas (ha.),36,NaN,NaN,NaN,NaN,NaN,5,...,1,2,3,NaN,5,2,4,5,NaN,5
15,NaN,NaN,Rendimiento (Kg./ha.),25850,NaN,NaN,NaN,NaN,NaN,27,...,27.3,27.5,27,NaN,25,22.15,25,25,NaN,25.6
16,NaN,NaN,Produccion (t.),930.6,NaN,NaN,NaN,NaN,NaN,135,...,27.3,55,81,NaN,125,44.3,100,125,NaN,128
17,NaN,NaN,Precio Chacra (S/Kg.),2.481,NaN,NaN,NaN,NaN,NaN,1.8,...,3,2.1,1.8,NaN,2.1,4.2,2.04,2,NaN,4
18,14030020108,AJI LIMO (CAPSICUM CHINENSE),Sup.Verde (ha.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,1,1,1,0,1,2,2,2
19,NaN,NaN,Siembras (ha.),1,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Inspeccionar encabezados y estructura de los cultivos

pd.set_option("display.max_columns", 25)
pd.set_option("display.width", 200)

print("ENCABEZADOS Y PERÍODOS")
display(df_muestra.iloc[7:12, :])

print("\nPRIMER CULTIVO Y SUS VARIABLES")
display(df_muestra.iloc[10:19, :])

print("\nÚLTIMAS FILAS DEL ARCHIVO")
display(df_muestra.tail(10))

ENCABEZADOS Y PERÍODOS

             0             1                2            3         4    5    6    7    8         9    10   11   12   13   14   15   16   17   18   19   20
7     2024-2025           NaN              NaN          NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8           NaN           NaN              NaN          NaN       NaN  NaN  NaN  NaN  NaN  COSECHAS  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9           NaN           NaN              NaN          NaN  SIEMBRAS  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  COD.CULTIVO       CULTIVO        VARIABLES  TOTAL EJEC.       AGO  SET  OCT  NOV  DIC       ENE  FEB  MAR  ABR  MAY  JUN  JUL  AGO  SET  OCT  NOV  DIC
11  14030020101  AJI AMARILLO  Sup.Verde (ha.)          NaN        16   14   13   12   10        10   10   10   19   16   16   11   34   38   41   50   57

PRIMER CULTIVO Y SUS VARIABLES

             0                             1                      2            3    4    5    6    7    8    9     10    11    12   13   14   15     16    17   18   19    20
10  COD.CULTIVO                       CULTIVO              VARIABLES  TOTAL EJEC.  AGO  SET  OCT  NOV  DIC  ENE   FEB   MAR   ABR  MAY  JUN  JUL    AGO   SET  OCT  NOV   DIC
11  14030020101                  AJI AMARILLO        Sup.Verde (ha.)          NaN   16   14   13   12   10   10    10    10    19   16   16   11     34    38   41   50    57
12          NaN                           NaN         Siembras (ha.)           35    7    2  NaN    1  NaN    5     4     5    11  NaN  NaN  NaN    NaN   NaN  NaN  NaN   NaN
13          NaN                           NaN      Sup Perdida (ha.)            4  NaN  NaN  NaN  NaN  NaN  NaN   NaN     4   NaN  NaN  NaN  NaN    NaN   NaN  NaN  NaN   NaN
14          NaN                           NaN         Cosechas (ha.)           36  NaN  NaN  NaN  NaN  NaN    5     4     1     2    3  NaN    5      2     4    5  NaN     5
15          NaN                           NaN  Rendimiento (Kg./ha.)        25850  NaN  NaN  NaN  NaN  NaN   27  27.5  27.3  27.5   27  NaN   25  22.15    25   25  NaN  25.6
16          NaN                           NaN        Produccion (t.)        930.6  NaN  NaN  NaN  NaN  NaN  135   110  27.3    55   81  NaN  125   44.3   100  125  NaN   128
17          NaN                           NaN  Precio Chacra (S/Kg.)        2.481  NaN  NaN  NaN  NaN  NaN  1.8   2.8     3   2.1  1.8  NaN  2.1    4.2  2.04    2  NaN     4
18  14030020108  AJI LIMO (CAPSICUM CHINENSE)        Sup.Verde (ha.)          NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN     1     1    1    1    1      0     1    2    2     2

ÚLTIMAS FILAS DEL ARCHIVO

              0                     1                      2          3    4    5    6    7    8    9       10   11      12   13      14   15     16   17    18      19    20
294          NaN                   NaN         Cosechas (ha.)      98.15  NaN  NaN  NaN  NaN  NaN    5       7    6      11    4       7    4     11    5     7    2.15    29
295          NaN                   NaN  Rendimiento (Kg./ha.)  45234.844  NaN  NaN  NaN  NaN  NaN   46  46.429   46  45.455   45  44.571   45     45   45    45  45.023    45
296          NaN                   NaN        Produccion (t.)     4439.8  NaN  NaN  NaN  NaN  NaN  230     325  276     500  180     312  180    495  225   315    96.8  1305
297          NaN                   NaN  Precio Chacra (S/Kg.)      0.776  NaN  NaN  NaN  NaN  NaN  0.6     0.6  0.9     0.7  0.8     0.7  0.8    0.7  0.8  1.17     0.7   0.8
298  14060070000  ZARANDAJA GRANO SECO        Sup.Verde (ha.)        NaN    8    4    0  NaN  NaN  NaN     NaN  NaN      11   11      11   11      0  NaN   NaN     NaN   NaN
299          NaN                   NaN         Siembras (ha.)         11  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN      11  NaN     NaN  NaN    NaN  NaN   NaN     NaN   NaN
300          NaN                   NaN         Cosechas (ha.)         11  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN     NaN  NaN     NaN  NaN     11  NaN   NaN     NaN   NaN
301          NaN                   NaN  Rendimiento (Kg./ha.)   1818.181  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN     NaN  NaN     NaN  NaN  1.818  NaN   NaN     NaN   NaN
302          NaN                   NaN        Produccion (t.)         20  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN     NaN  NaN     NaN  NaN     20  NaN   NaN     NaN   NaN
303          NaN                   NaN  Precio Chacra (S/Kg.)        2.5  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN     NaN  NaN     NaN  NaN    2.5  NaN   NaN     NaN   NaN

In [5]:
# Identificar columnas y períodos exactos

print("ENCABEZADOS DE LA FILA 10")
for columna in range(df_muestra.shape[1]):
    print(
        f"Columna {columna}: "
        f"{repr(df_muestra.iloc[10, columna])}"
    )

print("\nFILAS ANTERIORES AL ENCABEZADO")
for fila in range(7, 11):
    print(f"\nFila {fila}:")
    for columna in range(df_muestra.shape[1]):
        valor = df_muestra.iloc[fila, columna]
        if pd.notna(valor):
            print(f"  Columna {columna}: {repr(valor)}")

ENCABEZADOS DE LA FILA 10
Columna 0: 'COD.CULTIVO'
Columna 1: 'CULTIVO'
Columna 2: 'VARIABLES'
Columna 3: 'TOTAL EJEC.'
Columna 4: 'AGO'
Columna 5: 'SET'
Columna 6: 'OCT'
Columna 7: 'NOV'
Columna 8: 'DIC'
Columna 9: 'ENE'
Columna 10: 'FEB'
Columna 11: 'MAR'
Columna 12: 'ABR'
Columna 13: 'MAY'
Columna 14: 'JUN'
Columna 15: 'JUL'
Columna 16: 'AGO'
Columna 17: 'SET'
Columna 18: 'OCT'
Columna 19: 'NOV'
Columna 20: 'DIC'

FILAS ANTERIORES AL ENCABEZADO

Fila 7:
  Columna 0: '2024-2025'

Fila 8:
  Columna 9: 'COSECHAS'

Fila 9:
  Columna 4: 'SIEMBRAS'

Fila 10:
  Columna 0: 'COD.CULTIVO'
  Columna 1: 'CULTIVO'
  Columna 2: 'VARIABLES'
  Columna 3: 'TOTAL EJEC.'
  Columna 4: 'AGO'
  Columna 5: 'SET'
  Columna 6: 'OCT'
  Columna 7: 'NOV'
  Columna 8: 'DIC'
  Columna 9: 'ENE'
  Columna 10: 'FEB'
  Columna 11: 'MAR'
  Columna 12: 'ABR'
  Columna 13: 'MAY'
  Columna 14: 'JUN'
  Columna 15: 'JUL'
  Columna 16: 'AGO'
  Columna 17: 'SET'
  Columna 18: 'OCT'
  Columna 19: 'NOV'
  Columna 20: 'DIC'

In [6]:
# Comparar la estructura de los archivos provinciales

for archivo in archivos:
    excel = pd.ExcelFile(archivo)

    print(f"\n{'=' * 65}")
    print(f"ARCHIVO: {archivo.name}")
    print(f"TOTAL DE HOJAS: {len(excel.sheet_names)}")

    for hoja in excel.sheet_names:
        df = pd.read_excel(
            archivo,
            sheet_name=hoja,
            header=None
        )

        # Buscar la fila que contiene los encabezados
        filas_encabezado = []

        for i in range(min(25, len(df))):
            valores = df.iloc[i].astype(str).str.upper()

            if valores.str.contains(
                "COD.CULTIVO", regex=False
            ).any():
                filas_encabezado.append(i)

        print(
            f"  Hoja: {hoja} | "
            f"Filas: {df.shape[0]} | "
            f"Columnas: {df.shape[1]} | "
            f"Encabezado: {filas_encabezado}"
        )

=================================================================
ARCHIVO: PROVINCIA ASCOPE_2024-2025.xlsx
TOTAL DE HOJAS: 9
  Hoja: Ascope | Filas: 60 | Columnas: 21 | Encabezado: [10]
  Hoja: Casa Grande | Filas: 77 | Columnas: 21 | Encabezado: [10]
  Hoja: Chicama | Filas: 108 | Columnas: 21 | Encabezado: [10]
  Hoja: Chocope | Filas: 81 | Columnas: 21 | Encabezado: [10]
  Hoja: Magdalena de Cao | Filas: 51 | Columnas: 21 | Encabezado: [10]
  Hoja: Paijan | Filas: 149 | Columnas: 21 | Encabezado: [10]
  Hoja: Razuri | Filas: 183 | Columnas: 21 | Encabezado: [10]
  Hoja: Santiago de Cao | Filas: 95 | Columnas: 21 | Encabezado: [10]
  Hoja: Provincia Ascope | Filas: 260 | Columnas: 21 | Encabezado: [10]

=================================================================
ARCHIVO: PROVINCIA CHEPEN_2024-2025.xlsx
TOTAL DE HOJAS: 4
  Hoja: Chepen | Filas: 184 | Columnas: 21 | Encabezado: [10]
  Hoja: Pacanga | Filas: 258 | Columnas: 21 | Encabezado: [10]
  Hoja: Pueblo Nuevo | Filas: 130 | Columnas: 21 | Encabezado: [10]
  Hoja: Provincia Chepen | Filas: 283 | Columnas: 21 | Encabezado: [10]

=================================================================
ARCHIVO: PROVINCIA GRAN_CHIMU_2024-2025.xlsx
TOTAL DE HOJAS: 5
  Hoja: Cascas | Filas: 227 | Columnas: 21 | Encabezado: [10]
  Hoja: Lucma | Filas: 185 | Columnas: 21 | Encabezado: [10]
  Hoja: Marmot | Filas: 162 | Columnas: 21 | Encabezado: [10]
  Hoja: Sayapullo | Filas: 175 | Columnas: 21 | Encabezado: [10]
  Hoja: Provincia Gran Chimu | Filas: 234 | Columnas: 21 | Encabezado: [10]

=================================================================
ARCHIVO: PROVINCIA PACASMAYO_2024-2025.xlsx
TOTAL DE HOJAS: 6
  Hoja: San Pedro de Lloc | Filas: 147 | Columnas: 21 | Encabezado: [10]
  Hoja: Guadalupe | Filas: 73 | Columnas: 21 | Encabezado: [10]
  Hoja: Jequetepeque | Filas: 73 | Columnas: 21 | Encabezado: [10]
  Hoja: Pacasmayo | Filas: 29 | Columnas: 21 | Encabezado: [10]
  Hoja: San Jose | Filas: 130 | Columnas: 21 | Encabezado: [10]
  Hoja: Provincia Pacasmayo | Filas: 189 | Columnas: 21 | Encabezado: [10]

=================================================================
ARCHIVO: PROVINCIA TRUJILLO_2024-2025.xlsx
TOTAL DE HOJAS: 10
  Hoja: Trujillo | Filas: 181 | Columnas: 21 | Encabezado: [10]
  Hoja: El Porvenir | Filas: 23 | Columnas: 21 | Encabezado: [10]
  Hoja: Huanchaco | Filas: 235 | Columnas: 21 | Encabezado: [10]
  Hoja: Laredo | Filas: 308 | Columnas: 21 | Encabezado: [10]
  Hoja: Moche | Filas: 239 | Columnas: 21 | Encabezado: [10]
  Hoja: Poroto | Filas: 202 | Columnas: 21 | Encabezado: [10]
  Hoja: Salaverry | Filas: 44 | Columnas: 21 | Encabezado: [10]
  Hoja: Simbal | Filas: 227 | Columnas: 21 | Encabezado: [10]
  Hoja: Victor Larco | Filas: 118 | Columnas: 21 | Encabezado: [10]
  Hoja: Provincia Trujillo | Filas: 422 | Columnas: 21 | Encabezado: [10]

=================================================================
ARCHIVO: PROVINCIA VIRU_2024-2025.xlsx
TOTAL DE HOJAS: 4
  Hoja: Viru | Filas: 304 | Columnas: 21 | Encabezado: [10]
  Hoja: Chao | Filas: 290 | Columnas: 21 | Encabezado: [10]
  Hoja: Guadalupito | Filas: 158 | Columnas: 21 | Encabezado: [10]
  Hoja: Provincia Viru | Filas: 386 | Columnas: 21 | Encabezado: [10]

In [7]:
from openpyxl import load_workbook

archivo = ruta / "PROVINCIA VIRU_2024-2025.xlsx"

libro = load_workbook(
    archivo,
    data_only=False,
    read_only=True
)

hoja = libro["Viru"]

print("ENCABEZADOS ORIGINALES")
for fila in range(1, 12):
    valores = [
        f"{hoja.cell(fila, col).coordinate}: "
        f"{hoja.cell(fila, col).value}"
        for col in range(1, 22)
        if hoja.cell(fila, col).value is not None
    ]

    print(f"Fila {fila}: {' | '.join(valores)}")

print("\nFÓRMULAS DEL TOTAL EJECUTADO")

for fila in range(12, 19):
    print(
        f"Fila {fila}:",
        hoja.cell(fila, 4).value
    )

libro.close()

ENCABEZADOS ORIGINALES
Fila 1: A1: FECHA :  | B1: =NOW()
Fila 2:
Fila 3: A3: DEPARTAMENTO | B3: PROVINCIA  | C3: DISTRITO
Fila 4: A4: LA LIBERTAD | B4: VIRU | C4: VIRU
Fila 5:
Fila 6: A6: EJECUCION Y PERSPECTIVAS DE LA INFORMACION AGRICOLA
Fila 7: A7: CAMPAÑA AGRICOLA:
Fila 8: A8: 2024-2025
Fila 9: J9: COSECHAS
Fila 10: E10: SIEMBRAS
Fila 11: A11: COD.CULTIVO | B11: CULTIVO | C11: VARIABLES | D11: TOTAL EJEC. | E11: AGO | F11: SET | G11: OCT | H11: NOV | I11: DIC | J11: ENE | K11: FEB | L11: MAR | M11: ABR | N11: MAY | O11: JUN | P11: JUL | Q11: AGO | R11: SET | S11: OCT | T11: NOV | U11: DIC

FÓRMULAS DEL TOTAL EJECUTADO
Fila 12: None
Fila 13: 35
Fila 14: 4
Fila 15: 36
Fila 16: 25850
Fila 17: 930.6
Fila 18: 2.481

In [8]:
# Verificar períodos y valores del primer cultivo

print("CAMPAÑA AGRÍCOLA:")
print(df_muestra.iloc[7, 0])

print("\nMESES Y VALORES DEL PRIMER CULTIVO:")

for col in range(3, df_muestra.shape[1]):
    mes = df_muestra.iloc[10, col]
    valor = df_muestra.iloc[16, col]

    print(f"Columna {col}: {mes} → Producción: {valor}")

CAMPAÑA AGRÍCOLA:
2024-2025

MESES Y VALORES DEL PRIMER CULTIVO:
Columna 3: TOTAL EJEC. → Producción: 930.6
Columna 4: AGO → Producción: nan
Columna 5: SET → Producción: nan
Columna 6: OCT → Producción: nan
Columna 7: NOV → Producción: nan
Columna 8: DIC → Producción: nan
Columna 9: ENE → Producción: 135
Columna 10: FEB → Producción: 110
Columna 11: MAR → Producción: 27.3
Columna 12: ABR → Producción: 55
Columna 13: MAY → Producción: 81
Columna 14: JUN → Producción: nan
Columna 15: JUL → Producción: 125
Columna 16: AGO → Producción: 44.3
Columna 17: SET → Producción: 100
Columna 18: OCT → Producción: 125
Columna 19: NOV → Producción: nan
Columna 20: DIC → Producción: 128

In [9]:
# Comparar producción total con los períodos mensuales

import pandas as pd

fila_produccion = df_muestra.iloc[16]

total_ejecutado = pd.to_numeric(
    fila_produccion.iloc[3],
    errors="coerce"
)

# Agosto a diciembre (primer bloque)
bloque_1 = pd.to_numeric(
    fila_produccion.iloc[4:9],
    errors="coerce"
)

# Enero a diciembre (segundo bloque)
bloque_2 = pd.to_numeric(
    fila_produccion.iloc[9:21],
    errors="coerce"
)

print("Total ejecutado:", total_ejecutado)
print("Suma agosto-diciembre:", bloque_1.sum())
print("Suma enero-diciembre:", bloque_2.sum())
print("Suma de los 17 meses:",
      bloque_1.sum() + bloque_2.sum())

Total ejecutado: 930.6
Suma agosto-diciembre: 0.0
Suma enero-diciembre: 930.6
Suma de los 17 meses: 930.6

In [10]:
# Verificar los totales de producción de todos los cultivos

resultados = []

for i in range(11, len(df_muestra)):

    variable = str(df_muestra.iloc[i, 2]).strip().lower()

    if variable.startswith("produccion") or variable.startswith("producción"):

        total = pd.to_numeric(
            df_muestra.iloc[i, 3],
            errors="coerce"
        )

        meses = pd.to_numeric(
            df_muestra.iloc[i, 9:21],
            errors="coerce"
        )

        suma_meses = meses.sum(min_count=1)

        diferencia = (
            total - suma_meses
            if pd.notna(total) and pd.notna(suma_meses)
            else float("nan")
        )

        resultados.append({
            "fila_excel": i + 1,
            "total_ejecutado": total,
            "suma_12_meses": suma_meses,
            "diferencia": diferencia
        })

df_verificacion = pd.DataFrame(resultados)

print("Registros de producción encontrados:", len(df_verificacion))

display(df_verificacion.head(15))

print("\nRegistros con diferencias mayores a 0.01:")

diferencias = df_verificacion[
    df_verificacion["diferencia"].abs() > 0.01
]

print(len(diferencias))
display(diferencias.head(10))

Registros de producción encontrados: 50

    fila_excel  total_ejecutado  suma_12_meses    diferencia
0           17          930.600        930.600  0.000000e+00
1           23           14.000         14.000  0.000000e+00
2           30        20730.800      20730.800  0.000000e+00
3           36        11707.900      11707.900  1.818989e-12
4           42        41545.129      41545.129  0.000000e+00
5           48           32.000         32.000  0.000000e+00
6           55         6827.000       6827.000  0.000000e+00
7           61          418.000        418.000  0.000000e+00
8           67         1115.000       1115.000  0.000000e+00
9           72            1.440          1.440  0.000000e+00
10          78          287.100        287.100  5.684342e-14
11          85        33950.760      33950.760  7.275958e-12
12          92          600.000        600.000  0.000000e+00
13          98           59.100         59.100  0.000000e+00
14         105          291.700        291.700  0.000000e+00

Registros con diferencias mayores a 0.01:
0

Empty DataFrame
Columns: [fila_excel, total_ejecutado, suma_12_meses, diferencia]
Index: []

In [11]:
# Validación de producción en todos los Excel provinciales

resultados_globales = []

for archivo in archivos:
    excel = pd.ExcelFile(archivo)

    for hoja in excel.sheet_names:
        df = pd.read_excel(
            archivo,
            sheet_name=hoja,
            header=None
        )

        for i in range(11, len(df)):

            variable = str(df.iloc[i, 2]).strip().lower()

            if variable.startswith(("produccion", "producción")):

                total = pd.to_numeric(
                    df.iloc[i, 3],
                    errors="coerce"
                )

                meses = pd.to_numeric(
                    df.iloc[i, 9:21],
                    errors="coerce"
                )

                suma = meses.sum(min_count=1)

                diferencia = (
                    abs(total - suma)
                    if pd.notna(total) and pd.notna(suma)
                    else None
                )

                resultados_globales.append({
                    "archivo": archivo.name,
                    "hoja": hoja,
                    "fila_excel": i + 1,
                    "total": total,
                    "suma_meses": suma,
                    "diferencia": diferencia
                })

df_global = pd.DataFrame(resultados_globales)

print("Total de registros evaluados:", len(df_global))

print(
    "Registros con diferencias mayores a 0.01:",
    (df_global["diferencia"] > 0.01).sum()
)

print(
    "Registros sin comparación válida:",
    df_global["diferencia"].isna().sum()
)

display(
    df_global.groupby("archivo").agg(
        registros=("fila_excel", "count"),
        diferencias=("diferencia", lambda x: (x > 0.01).sum()),
        sin_comparacion=("diferencia", lambda x: x.isna().sum())
    ).reset_index()
)

Total de registros evaluados: 1100
Registros con diferencias mayores a 0.01: 0
Registros sin comparación válida: 0

                               archivo  registros  diferencias  sin_comparacion
0      PROVINCIA ASCOPE_2024-2025.xlsx        174            0                0
1      PROVINCIA CHEPEN_2024-2025.xlsx        144            0                0
2  PROVINCIA GRAN_CHIMU_2024-2025.xlsx        169            0                0
3   PROVINCIA PACASMAYO_2024-2025.xlsx        100            0                0
4    PROVINCIA TRUJILLO_2024-2025.xlsx        327            0                0
5        PROVINCIA VIRU_2024-2025.xlsx        186            0                0

In [12]:
# Paso 6.9 - Clasificar hojas distritales y provinciales

clasificacion = []

for archivo in archivos:
    excel = pd.ExcelFile(archivo)

    for hoja in excel.sheet_names:

        tipo = (
            "RESUMEN PROVINCIAL"
            if hoja.strip().lower().startswith("provincia")
            else "DISTRITO"
        )

        clasificacion.append({
            "archivo": archivo.name,
            "hoja": hoja,
            "tipo": tipo
        })

df_hojas = pd.DataFrame(clasificacion)

print("Total de hojas:", len(df_hojas))

print("\nCantidad por tipo:")
print(df_hojas["tipo"].value_counts())

display(df_hojas)

Total de hojas: 38

Cantidad por tipo:
tipo
DISTRITO              32
RESUMEN PROVINCIAL     6
Name: count, dtype: int64

                                archivo                  hoja                tipo
0       PROVINCIA ASCOPE_2024-2025.xlsx                Ascope            DISTRITO
1       PROVINCIA ASCOPE_2024-2025.xlsx           Casa Grande            DISTRITO
2       PROVINCIA ASCOPE_2024-2025.xlsx               Chicama            DISTRITO
3       PROVINCIA ASCOPE_2024-2025.xlsx               Chocope            DISTRITO
4       PROVINCIA ASCOPE_2024-2025.xlsx      Magdalena de Cao            DISTRITO
5       PROVINCIA ASCOPE_2024-2025.xlsx                Paijan            DISTRITO
6       PROVINCIA ASCOPE_2024-2025.xlsx                Razuri            DISTRITO
7       PROVINCIA ASCOPE_2024-2025.xlsx       Santiago de Cao            DISTRITO
8       PROVINCIA ASCOPE_2024-2025.xlsx      Provincia Ascope  RESUMEN PROVINCIAL
9       PROVINCIA CHEPEN_2024-2025.xlsx                Chepen            DISTRITO
10      PROVINCIA CHEPEN_2024-2025.xlsx               Pacanga            DISTRITO
11      PROVINCIA CHEPEN_2024-2025.xlsx          Pueblo Nuevo            DISTRITO
12      PROVINCIA CHEPEN_2024-2025.xlsx      Provincia Chepen  RESUMEN PROVINCIAL
13  PROVINCIA GRAN_CHIMU_2024-2025.xlsx                Cascas            DISTRITO
14  PROVINCIA GRAN_CHIMU_2024-2025.xlsx                 Lucma            DISTRITO
15  PROVINCIA GRAN_CHIMU_2024-2025.xlsx                Marmot            DISTRITO
16  PROVINCIA GRAN_CHIMU_2024-2025.xlsx             Sayapullo            DISTRITO
17  PROVINCIA GRAN_CHIMU_2024-2025.xlsx  Provincia Gran Chimu  RESUMEN PROVINCIAL
18   PROVINCIA PACASMAYO_2024-2025.xlsx     San Pedro de Lloc            DISTRITO
19   PROVINCIA PACASMAYO_2024-2025.xlsx             Guadalupe            DISTRITO
20   PROVINCIA PACASMAYO_2024-2025.xlsx          Jequetepeque            DISTRITO
21   PROVINCIA PACASMAYO_2024-2025.xlsx             Pacasmayo            DISTRITO
22   PROVINCIA PACASMAYO_2024-2025.xlsx              San Jose            DISTRITO
23   PROVINCIA PACASMAYO_2024-2025.xlsx   Provincia Pacasmayo  RESUMEN PROVINCIAL
24    PROVINCIA TRUJILLO_2024-2025.xlsx              Trujillo            DISTRITO
25    PROVINCIA TRUJILLO_2024-2025.xlsx           El Porvenir            DISTRITO
26    PROVINCIA TRUJILLO_2024-2025.xlsx             Huanchaco            DISTRITO
27    PROVINCIA TRUJILLO_2024-2025.xlsx                Laredo            DISTRITO
28    PROVINCIA TRUJILLO_2024-2025.xlsx                 Moche            DISTRITO
29    PROVINCIA TRUJILLO_2024-2025.xlsx                Poroto            DISTRITO
30    PROVINCIA TRUJILLO_2024-2025.xlsx             Salaverry            DISTRITO
31    PROVINCIA TRUJILLO_2024-2025.xlsx                Simbal            DISTRITO
32    PROVINCIA TRUJILLO_2024-2025.xlsx          Victor Larco            DISTRITO
33    PROVINCIA TRUJILLO_2024-2025.xlsx    Provincia Trujillo  RESUMEN PROVINCIAL
34        PROVINCIA VIRU_2024-2025.xlsx                  Viru            DISTRITO
35        PROVINCIA VIRU_2024-2025.xlsx                  Chao            DISTRITO
36        PROVINCIA VIRU_2024-2025.xlsx           Guadalupito            DISTRITO
37        PROVINCIA VIRU_2024-2025.xlsx        Provincia Viru  RESUMEN PROVINCIAL

In [13]:
# Paso 6.10 - Extraer registros agrícolas de las hojas distritales

import pandas as pd

registros = []

for archivo in archivos:

    # Obtener provincia desde el nombre del archivo
    provincia = (
        archivo.stem
        .replace("PROVINCIA ", "")
        .replace("_2024-2025", "")
        .replace("_", " ")
    )

    excel = pd.ExcelFile(archivo)

    for hoja in excel.sheet_names:

        # Evitar incluir resúmenes provinciales
        if hoja.strip().lower().startswith("provincia"):
            continue

        df = pd.read_excel(
            archivo,
            sheet_name=hoja,
            header=None
        )

        codigo_actual = None
        cultivo_actual = None

        for i in range(11, len(df)):

            codigo = df.iloc[i, 0]
            cultivo = df.iloc[i, 1]
            variable = df.iloc[i, 2]

            # Identificar nuevo cultivo
            if pd.notna(codigo) and pd.notna(cultivo):
                codigo_actual = str(codigo).strip()
                cultivo_actual = str(cultivo).strip()

            if pd.isna(variable) or cultivo_actual is None:
                continue

            nombre_variable = str(variable).strip()

            # Extraer los valores de las 17 columnas mensuales
            for columna in range(4, 21):

                mes = df.iloc[10, columna]
                valor = pd.to_numeric(
                    df.iloc[i, columna],
                    errors="coerce"
                )

                if pd.notna(valor):

                    registros.append({
                        "provincia": provincia,
                        "distrito": hoja,
                        "codigo_cultivo": codigo_actual,
                        "cultivo": cultivo_actual,
                        "variable": nombre_variable,
                        "columna_origen": columna,
                        "mes_origen": str(mes).strip(),
                        "valor": float(valor),
                        "archivo_origen": archivo.name
                    })

df_agricola = pd.DataFrame(registros)

print("Total de registros extraídos:", len(df_agricola))
print("Columnas:", df_agricola.columns.tolist())

display(df_agricola.head(20))

Total de registros extraídos: 27864
Columnas: ['provincia', 'distrito', 'codigo_cultivo', 'cultivo', 'variable', 'columna_origen', 'mes_origen', 'valor', 'archivo_origen']

   provincia distrito codigo_cultivo       cultivo         variable  columna_origen mes_origen  valor                   archivo_origen
0     ASCOPE   Ascope    14030020101  AJI AMARILLO  Sup.Verde (ha.)               4        AGO   10.0  PROVINCIA ASCOPE_2024-2025.xlsx
1     ASCOPE   Ascope    14030020101  AJI AMARILLO  Sup.Verde (ha.)               5        SET   10.0  PROVINCIA ASCOPE_2024-2025.xlsx
2     ASCOPE   Ascope    14030020101  AJI AMARILLO  Sup.Verde (ha.)               6        OCT    6.0  PROVINCIA ASCOPE_2024-2025.xlsx
3     ASCOPE   Ascope    14030020101  AJI AMARILLO  Sup.Verde (ha.)               7        NOV    0.0  PROVINCIA ASCOPE_2024-2025.xlsx
4     ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)               4        AGO    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
5     ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)               5        SET    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
6     ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)               6        OCT    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
7     ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)               7        NOV    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
8     ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)               8        DIC    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
9     ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)               9        ENE    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
10    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              10        FEB    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
11    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              11        MAR    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
12    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              12        ABR    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
13    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              13        MAY    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
14    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              14        JUN    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
15    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              15        JUL    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
16    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              16        AGO    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
17    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              17        SET    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
18    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              18        OCT    1.0  PROVINCIA ASCOPE_2024-2025.xlsx
19    ASCOPE   Ascope    12010010000       ALFALFA  Sup.Verde (ha.)              19        NOV    1.0  PROVINCIA ASCOPE_2024-2025.xlsx

In [14]:
# Paso 6.11 - Validar los registros extraídos

print("TOTAL DE REGISTROS:", len(df_agricola))

print("\nREGISTROS POR PROVINCIA:")
display(
    df_agricola.groupby("provincia")
    .size()
    .reset_index(name="registros")
)

print("\nVARIABLES AGRÍCOLAS IDENTIFICADAS:")
display(
    df_agricola["variable"]
    .value_counts()
    .reset_index()
)

print("\nCULTIVOS DIFERENTES:")
print(df_agricola["cultivo"].nunique())

print("\nVALORES NEGATIVOS:")
print((df_agricola["valor"] < 0).sum())

print("\nREGISTROS CON CAMPOS CRÍTICOS VACÍOS:")
print(
    df_agricola[
        ["provincia", "distrito", "cultivo",
         "variable", "valor"]
    ].isna().sum()
)

print("\nCÓDIGOS ASOCIADOS A MÁS DE UN CULTIVO:")
codigos = (
    df_agricola.groupby("codigo_cultivo")["cultivo"]
    .nunique()
)
print((codigos > 1).sum())

TOTAL DE REGISTROS: 27864

REGISTROS POR PROVINCIA:

    provincia  registros
0      ASCOPE       3430
1      CHEPEN       3190
2  GRAN CHIMU       3907
3   PACASMAYO       1817
4    TRUJILLO      10690
5        VIRU       4830

VARIABLES AGRÍCOLAS IDENTIFICADAS:

                variable  count
0        Sup.Verde (ha.)  12110
1        Produccion (t.)   4415
2  Precio Chacra (S/Kg.)   4415
3         Cosechas (ha.)   2548
4         Siembras (ha.)   2196
5  Rendimiento (Kg./ha.)   2157
6      Sup Perdida (ha.)     23

CULTIVOS DIFERENTES:
106

VALORES NEGATIVOS:
0

REGISTROS CON CAMPOS CRÍTICOS VACÍOS:
provincia    0
distrito     0
cultivo      0
variable     0
valor        0
dtype: int64

CÓDIGOS ASOCIADOS A MÁS DE UN CULTIVO:
0

In [15]:
# Verificar los cultivos principales del proyecto Danper

cultivos_principales = df_agricola[
    df_agricola["cultivo"].str.contains(
        "ESPARR|ALCACHOF",
        case=False,
        na=False
    )
]

print("REGISTROS DE ESPÁRRAGO Y ALCACHOFA:")
print(len(cultivos_principales))

print("\nCULTIVOS ENCONTRADOS:")
print(cultivos_principales["cultivo"].value_counts())

print("\nDISTRIBUCIÓN POR PROVINCIA:")
display(
    cultivos_principales.groupby(
        ["provincia", "cultivo"]
    ).size().reset_index(name="registros")
)

print("\nPRIMEROS REGISTROS:")
display(cultivos_principales.head(15))

REGISTROS DE ESPÁRRAGO Y ALCACHOFA:
829

CULTIVOS ENCONTRADOS:
cultivo
ESPARRAGO    719
ALCACHOFA    110
Name: count, dtype: int64

DISTRIBUCIÓN POR PROVINCIA:

   provincia    cultivo  registros
0     ASCOPE  ESPARRAGO        266
1     CHEPEN  ALCACHOFA         32
2     CHEPEN  ESPARRAGO        114
3  PACASMAYO  ESPARRAGO         90
4   TRUJILLO  ESPARRAGO        146
5       VIRU  ALCACHOFA         78
6       VIRU  ESPARRAGO        103

PRIMEROS REGISTROS:

    provincia     distrito codigo_cultivo    cultivo         variable  columna_origen mes_origen  valor                   archivo_origen
321    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)               4        AGO   40.0  PROVINCIA ASCOPE_2024-2025.xlsx
322    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)               5        SET   40.0  PROVINCIA ASCOPE_2024-2025.xlsx
323    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)               6        OCT   40.0  PROVINCIA ASCOPE_2024-2025.xlsx
324    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)               7        NOV   40.0  PROVINCIA ASCOPE_2024-2025.xlsx
325    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)               8        DIC   40.0  PROVINCIA ASCOPE_2024-2025.xlsx
326    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)               9        ENE   42.0  PROVINCIA ASCOPE_2024-2025.xlsx
327    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)              10        FEB   42.0  PROVINCIA ASCOPE_2024-2025.xlsx
328    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)              11        MAR   42.0  PROVINCIA ASCOPE_2024-2025.xlsx
329    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)              12        ABR   42.0  PROVINCIA ASCOPE_2024-2025.xlsx
330    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)              13        MAY   42.0  PROVINCIA ASCOPE_2024-2025.xlsx
331    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)              14        JUN   42.0  PROVINCIA ASCOPE_2024-2025.xlsx
332    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)              15        JUL   42.0  PROVINCIA ASCOPE_2024-2025.xlsx
333    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)              16        AGO   42.0  PROVINCIA ASCOPE_2024-2025.xlsx
334    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)              17        SET   42.0  PROVINCIA ASCOPE_2024-2025.xlsx
335    ASCOPE  Casa Grande    15010010000  ESPARRAGO  Sup.Verde (ha.)              18        OCT   42.0  PROVINCIA ASCOPE_2024-2025.xlsx

In [16]:
# Paso 6.13 - Investigar registros sin código de cultivo

sin_codigo = df_agricola[
    df_agricola["codigo_cultivo"].isna()
].copy()

print("Total de registros sin código:", len(sin_codigo))

print("\nDistribución por archivo, hoja y cultivo:")
display(
    sin_codigo.groupby(
        ["archivo_origen", "distrito", "cultivo"],
        dropna=False
    ).size().reset_index(name="registros")
)

print("\nPrimeros registros encontrados:")
display(sin_codigo.head(15))

Total de registros sin código: 0

Distribución por archivo, hoja y cultivo:

Empty DataFrame
Columns: [archivo_origen, distrito, cultivo, registros]
Index: []

Primeros registros encontrados:

Empty DataFrame
Columns: [provincia, distrito, codigo_cultivo, cultivo, variable, columna_origen, mes_origen, valor, archivo_origen]
Index: []

In [17]:
# Paso 6.14 - Detectar códigos vacíos y espacios

codigos_vacios = df_agricola[
    df_agricola["codigo_cultivo"].isna()
    | (
        df_agricola["codigo_cultivo"]
        .astype(str)
        .str.strip()
        == ""
    )
].copy()

print("Total de registros sin código:", len(codigos_vacios))

print("\nDistribución por cultivo:")
display(
    codigos_vacios.groupby(
        ["provincia", "distrito", "cultivo"]
    ).size().reset_index(name="registros")
)

print("\nPrimeros registros:")
display(codigos_vacios.head(15))

Total de registros sin código: 0

Distribución por cultivo:

Empty DataFrame
Columns: [provincia, distrito, cultivo, registros]
Index: []

Primeros registros:

Empty DataFrame
Columns: [provincia, distrito, codigo_cultivo, cultivo, variable, columna_origen, mes_origen, valor, archivo_origen]
Index: []

In [18]:
# Paso 6.15 - Identificar códigos sospechosos

print("Tipos de datos:")
print(df_agricola["codigo_cultivo"].map(type).value_counts())

print("\nCódigos más frecuentes:")
display(
    df_agricola["codigo_cultivo"]
    .astype(str)
    .value_counts()
    .head(15)
)

print("\nRegistros con códigos sospechosos:")

sospechosos = df_agricola[
    df_agricola["codigo_cultivo"]
    .astype(str)
    .str.strip()
    .str.lower()
    .isin(["none", "nan", "null", ""])
]

print("Total:", len(sospechosos))
display(sospechosos.head(15))

Tipos de datos:
codigo_cultivo
<class 'str'>    27864
Name: count, dtype: int64

Códigos más frecuentes:

codigo_cultivo
14010070000    1412
12010010000    1311
14050060000    1067
14040140000     825
13010230000     739
13010320000     729
15010010000     719
14030300000     719
13020120000     687
15010040000     606
14060030000     603
14030100000     591
14030180000     568
14030020101     546
14030060000     529
Name: count, dtype: int64

Registros con códigos sospechosos:
Total: 0

Empty DataFrame
Columns: [provincia, distrito, codigo_cultivo, cultivo, variable, columna_origen, mes_origen, valor, archivo_origen]
Index: []

In [19]:
# Paso 6.16 - Comprobación definitiva de códigos

codigos = df_agricola["codigo_cultivo"]

print("Total de registros:", len(df_agricola))
print("Códigos nulos:", codigos.isna().sum())
print("Códigos únicos:", codigos.nunique())

print("\nCódigos no numéricos:")
no_numericos = codigos[
    pd.to_numeric(codigos, errors="coerce").isna()
]

print("Cantidad:", len(no_numericos))
print(no_numericos.value_counts(dropna=False).head(15))

print("\nEjemplos:")
display(
    df_agricola.loc[
        no_numericos.index,
        ["provincia", "distrito", "cultivo", "codigo_cultivo"]
    ].head(15)
)

Total de registros: 27864
Códigos nulos: 0
Códigos únicos: 106

Códigos no numéricos:
Cantidad: 0
Series([], Name: count, dtype: int64)

Ejemplos:

Empty DataFrame
Columns: [provincia, distrito, cultivo, codigo_cultivo]
Index: []

In [20]:
# Paso 6.17 - Comparar encabezados temporales de los seis Excel

comparacion_periodos = []

for archivo in archivos:
    excel = pd.ExcelFile(archivo)

    for hoja in excel.sheet_names:
        if hoja.lower().startswith("provincia"):
            continue

        df = pd.read_excel(
            archivo,
            sheet_name=hoja,
            header=None
        )

        encabezados = tuple(
            str(x).strip()
            for x in df.iloc[10, 4:21]
        )

        comparacion_periodos.append({
            "archivo": archivo.name,
            "hoja": hoja,
            "meses": encabezados
        })

df_periodos = pd.DataFrame(comparacion_periodos)

print("Hojas revisadas:", len(df_periodos))
print("Patrones de encabezado distintos:",
      df_periodos["meses"].nunique())

for patron in df_periodos["meses"].unique():
    print("\nPatrón:", patron)

Hojas revisadas: 32
Patrones de encabezado distintos: 1

Patrón: ('AGO', 'SET', 'OCT', 'NOV', 'DIC', 'ENE', 'FEB', 'MAR', 'ABR', 'MAY', 'JUN', 'JUL', 'AGO', 'SET', 'OCT', 'NOV', 'DIC')