In [1]:
from pathlib import Path
import pandas as pd

ruta = Path.home() / "proyecto_danper/datasets/produccion"

archivos = sorted(ruta.glob("*.xlsx"))

print("Total de archivos:", len(archivos))

for archivo in archivos:
    print("\nArchivo:", archivo.name)
    excel = pd.ExcelFile(archivo)
    print("Hojas disponibles:", excel.sheet_names)

Total de archivos: 6

Archivo: PROVINCIA ASCOPE_2024-2025.xlsx
Hojas disponibles: ['Ascope', 'Casa Grande', 'Chicama', 'Chocope', 'Magdalena de Cao', 'Paijan', 'Razuri', 'Santiago de Cao', 'Provincia Ascope']

Archivo: PROVINCIA CHEPEN_2024-2025.xlsx
Hojas disponibles: ['Chepen', 'Pacanga', 'Pueblo Nuevo', 'Provincia Chepen']

Archivo: PROVINCIA GRAN_CHIMU_2024-2025.xlsx
Hojas disponibles: ['Cascas', 'Lucma', 'Marmot', 'Sayapullo', 'Provincia Gran Chimu']

Archivo: PROVINCIA PACASMAYO_2024-2025.xlsx
Hojas disponibles: ['San Pedro de Lloc', 'Guadalupe', 'Jequetepeque', 'Pacasmayo', 'San Jose', 'Provincia Pacasmayo']

Archivo: PROVINCIA TRUJILLO_2024-2025.xlsx
Hojas disponibles: ['Trujillo', 'El Porvenir', 'Huanchaco', 'Laredo', 'Moche', 'Poroto', 'Salaverry', 'Simbal', 'Victor Larco', 'Provincia Trujillo']

Archivo: PROVINCIA VIRU_2024-2025.xlsx
Hojas disponibles: ['Viru', 'Chao', 'Guadalupito', 'Provincia Viru']

In [3]:
# Inspeccionar las primeras filas de una hoja real

archivo = ruta / "PROVINCIA VIRU_2024-2025.xlsx"

df_muestra = pd.read_excel(
    archivo,
    sheet_name="Viru",
    header=None
)

print("Dimensiones:", df_muestra.shape)

display(df_muestra.head(20))

Dimensiones: (304, 21)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,FECHA :,2026-01-27 17:22:43.450000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DEPARTAMENTO,PROVINCIA,DISTRITO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LA LIBERTAD,VIRU,VIRU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,EJECUCION Y PERSPECTIVAS DE LA INFORMACION AGR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,CAMPAÑA AGRICOLA:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2024-2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COSECHAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,SIEMBRAS,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,COD.CULTIVO,CULTIVO,VARIABLES,TOTAL EJEC.,AGO,SET,OCT,NOV,DIC,ENE,...,MAR,ABR,MAY,JUN,JUL,AGO,SET,OCT,NOV,DIC
11,14030020101,AJI AMARILLO,Sup.Verde (ha.),NaN,16,14,13,12,10,10,...,10,19,16,16,11,34,38,41,50,57
12,NaN,NaN,Siembras (ha.),35,7,2,NaN,1,NaN,5,...,5,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,Sup Perdida (ha.),4,NaN,NaN,NaN,NaN,NaN,NaN,...,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,Cosechas (ha.),36,NaN,NaN,NaN,NaN,NaN,5,...,1,2,3,NaN,5,2,4,5,NaN,5
15,NaN,NaN,Rendimiento (Kg./ha.),25850,NaN,NaN,NaN,NaN,NaN,27,...,27.3,27.5,27,NaN,25,22.15,25,25,NaN,25.6
16,NaN,NaN,Produccion (t.),930.6,NaN,NaN,NaN,NaN,NaN,135,...,27.3,55,81,NaN,125,44.3,100,125,NaN,128
17,NaN,NaN,Precio Chacra (S/Kg.),2.481,NaN,NaN,NaN,NaN,NaN,1.8,...,3,2.1,1.8,NaN,2.1,4.2,2.04,2,NaN,4
18,14030020108,AJI LIMO (CAPSICUM CHINENSE),Sup.Verde (ha.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,1,1,1,0,1,2,2,2
19,NaN,NaN,Siembras (ha.),1,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Inspeccionar encabezados y estructura de los cultivos

pd.set_option("display.max_columns", 25)
pd.set_option("display.width", 200)

print("ENCABEZADOS Y PERÍODOS")
display(df_muestra.iloc[7:12, :])

print("\nPRIMER CULTIVO Y SUS VARIABLES")
display(df_muestra.iloc[10:19, :])

print("\nÚLTIMAS FILAS DEL ARCHIVO")
display(df_muestra.tail(10))

ENCABEZADOS Y PERÍODOS

             0             1                2            3         4    5    6    7    8         9    10   11   12   13   14   15   16   17   18   19   20
7     2024-2025           NaN              NaN          NaN       NaN  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8           NaN           NaN              NaN          NaN       NaN  NaN  NaN  NaN  NaN  COSECHAS  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
9           NaN           NaN              NaN          NaN  SIEMBRAS  NaN  NaN  NaN  NaN       NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10  COD.CULTIVO       CULTIVO        VARIABLES  TOTAL EJEC.       AGO  SET  OCT  NOV  DIC       ENE  FEB  MAR  ABR  MAY  JUN  JUL  AGO  SET  OCT  NOV  DIC
11  14030020101  AJI AMARILLO  Sup.Verde (ha.)          NaN        16   14   13   12   10        10   10   10   19   16   16   11   34   38   41   50   57

PRIMER CULTIVO Y SUS VARIABLES

             0                             1                      2            3    4    5    6    7    8    9     10    11    12   13   14   15     16    17   18   19    20
10  COD.CULTIVO                       CULTIVO              VARIABLES  TOTAL EJEC.  AGO  SET  OCT  NOV  DIC  ENE   FEB   MAR   ABR  MAY  JUN  JUL    AGO   SET  OCT  NOV   DIC
11  14030020101                  AJI AMARILLO        Sup.Verde (ha.)          NaN   16   14   13   12   10   10    10    10    19   16   16   11     34    38   41   50    57
12          NaN                           NaN         Siembras (ha.)           35    7    2  NaN    1  NaN    5     4     5    11  NaN  NaN  NaN    NaN   NaN  NaN  NaN   NaN
13          NaN                           NaN      Sup Perdida (ha.)            4  NaN  NaN  NaN  NaN  NaN  NaN   NaN     4   NaN  NaN  NaN  NaN    NaN   NaN  NaN  NaN   NaN
14          NaN                           NaN         Cosechas (ha.)           36  NaN  NaN  NaN  NaN  NaN    5     4     1     2    3  NaN    5      2     4    5  NaN     5
15          NaN                           NaN  Rendimiento (Kg./ha.)        25850  NaN  NaN  NaN  NaN  NaN   27  27.5  27.3  27.5   27  NaN   25  22.15    25   25  NaN  25.6
16          NaN                           NaN        Produccion (t.)        930.6  NaN  NaN  NaN  NaN  NaN  135   110  27.3    55   81  NaN  125   44.3   100  125  NaN   128
17          NaN                           NaN  Precio Chacra (S/Kg.)        2.481  NaN  NaN  NaN  NaN  NaN  1.8   2.8     3   2.1  1.8  NaN  2.1    4.2  2.04    2  NaN     4
18  14030020108  AJI LIMO (CAPSICUM CHINENSE)        Sup.Verde (ha.)          NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN     1     1    1    1    1      0     1    2    2     2

ÚLTIMAS FILAS DEL ARCHIVO

              0                     1                      2          3    4    5    6    7    8    9       10   11      12   13      14   15     16   17    18      19    20
294          NaN                   NaN         Cosechas (ha.)      98.15  NaN  NaN  NaN  NaN  NaN    5       7    6      11    4       7    4     11    5     7    2.15    29
295          NaN                   NaN  Rendimiento (Kg./ha.)  45234.844  NaN  NaN  NaN  NaN  NaN   46  46.429   46  45.455   45  44.571   45     45   45    45  45.023    45
296          NaN                   NaN        Produccion (t.)     4439.8  NaN  NaN  NaN  NaN  NaN  230     325  276     500  180     312  180    495  225   315    96.8  1305
297          NaN                   NaN  Precio Chacra (S/Kg.)      0.776  NaN  NaN  NaN  NaN  NaN  0.6     0.6  0.9     0.7  0.8     0.7  0.8    0.7  0.8  1.17     0.7   0.8
298  14060070000  ZARANDAJA GRANO SECO        Sup.Verde (ha.)        NaN    8    4    0  NaN  NaN  NaN     NaN  NaN      11   11      11   11      0  NaN   NaN     NaN   NaN
299          NaN                   NaN         Siembras (ha.)         11  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN      11  NaN     NaN  NaN    NaN  NaN   NaN     NaN   NaN
300          NaN                   NaN         Cosechas (ha.)         11  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN     NaN  NaN     NaN  NaN     11  NaN   NaN     NaN   NaN
301          NaN                   NaN  Rendimiento (Kg./ha.)   1818.181  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN     NaN  NaN     NaN  NaN  1.818  NaN   NaN     NaN   NaN
302          NaN                   NaN        Produccion (t.)         20  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN     NaN  NaN     NaN  NaN     20  NaN   NaN     NaN   NaN
303          NaN                   NaN  Precio Chacra (S/Kg.)        2.5  NaN  NaN  NaN  NaN  NaN  NaN     NaN  NaN     NaN  NaN     NaN  NaN    2.5  NaN   NaN     NaN   NaN

In [5]:
# Identificar columnas y períodos exactos

print("ENCABEZADOS DE LA FILA 10")
for columna in range(df_muestra.shape[1]):
    print(
        f"Columna {columna}: "
        f"{repr(df_muestra.iloc[10, columna])}"
    )

print("\nFILAS ANTERIORES AL ENCABEZADO")
for fila in range(7, 11):
    print(f"\nFila {fila}:")
    for columna in range(df_muestra.shape[1]):
        valor = df_muestra.iloc[fila, columna]
        if pd.notna(valor):
            print(f"  Columna {columna}: {repr(valor)}")

ENCABEZADOS DE LA FILA 10
Columna 0: 'COD.CULTIVO'
Columna 1: 'CULTIVO'
Columna 2: 'VARIABLES'
Columna 3: 'TOTAL EJEC.'
Columna 4: 'AGO'
Columna 5: 'SET'
Columna 6: 'OCT'
Columna 7: 'NOV'
Columna 8: 'DIC'
Columna 9: 'ENE'
Columna 10: 'FEB'
Columna 11: 'MAR'
Columna 12: 'ABR'
Columna 13: 'MAY'
Columna 14: 'JUN'
Columna 15: 'JUL'
Columna 16: 'AGO'
Columna 17: 'SET'
Columna 18: 'OCT'
Columna 19: 'NOV'
Columna 20: 'DIC'

FILAS ANTERIORES AL ENCABEZADO

Fila 7:
  Columna 0: '2024-2025'

Fila 8:
  Columna 9: 'COSECHAS'

Fila 9:
  Columna 4: 'SIEMBRAS'

Fila 10:
  Columna 0: 'COD.CULTIVO'
  Columna 1: 'CULTIVO'
  Columna 2: 'VARIABLES'
  Columna 3: 'TOTAL EJEC.'
  Columna 4: 'AGO'
  Columna 5: 'SET'
  Columna 6: 'OCT'
  Columna 7: 'NOV'
  Columna 8: 'DIC'
  Columna 9: 'ENE'
  Columna 10: 'FEB'
  Columna 11: 'MAR'
  Columna 12: 'ABR'
  Columna 13: 'MAY'
  Columna 14: 'JUN'
  Columna 15: 'JUL'
  Columna 16: 'AGO'
  Columna 17: 'SET'
  Columna 18: 'OCT'
  Columna 19: 'NOV'
  Columna 20: 'DIC'